# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
    - '*' 

pool:
  vmImage: 'ubuntu-latest'

variables:
  command: build
  projects: '$(solution)'
  configuration: '$(buildConfiguration)'
  versioningScheme: byEnvVar
  versionEnvVar: 'GitVersion.SemVer'
  buildConfiguration: 'Release'

steps:
- task: UseGitVersion@5
  displayName: gitversion
  inputs:
    versionSpec: '5.x'
    updateAssemblyInfo: false
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration) -p:Version=$(versionEnvVar)'
- task: DotNetCoreCLI@2
  displayName: Unit tests
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
