# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
    - master
    - develop
    - release/*
    - hotfix/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  command: build
  projects: '$(solution)'
  configuration: '$(buildConfiguration)'
  versioningScheme: byEnvVar
  projectToPackage: 'Breaker/Breaker.csproj'
  buildConfiguration: 'Release'
  GitVersion.SemVer: ''
  GitVersion.NuGetVersion: ''
  
# this pipeline has one implicit stage
steps:
  - task: UseGitVersion@5
    displayName: semversion
    inputs:
      versionSpec: '5.x'
      updateAssemblyInfo: false

  - task: DotNetCoreCLI@2 
    displayName: 'dotnet build' 
    inputs: 
      command: build
      arguments: '--configuration $(buildConfiguration) -p:FileVersion=$(GitVersion.NuGetVersion)  -p:Version=$(GitVersion.NuGetVersion)' 
      versioningScheme: byBuildNumber

  - task: DotNetCoreCLI@2
    displayName: Unit tests
    inputs:
      command: test
      arguments: '--configuration $(buildConfiguration)'
  - task: DotNetCoreCLI@2
    displayName: 'dotnet pack' 
    inputs: 
      command: pack
      packagesToPack: '$(projectToPackage)'
      versioningScheme: byEnvVar 
      versionEnvVar: '$(GitVersion.NuGetVersion)'
      packDirectory: $(Build.ArtifactStagingDirectory)