# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
    - master
    - develop
    - release/*
    - hotfix/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  projects: '$(solution)'
  configuration: '$(buildConfiguration)'
  projectToPackage: 'Breaker/Breaker.csproj'
  buildConfiguration: 'Release'

steps:
  - task: DotNetCoreCLI@2 
    displayName: 'Building' 
    inputs: 
      command: build
      arguments: '--configuration $(buildConfiguration)' 

  - task: DotNetCoreCLI@2
    displayName: Executing Tests
    inputs:
      command: test
      arguments: '--configuration $(buildConfiguration)'

  - task: DotNetCoreCLI@2
    displayName: 'Generating Artifact'
    inputs: 
      command: pack
      packagesToPack: '$(projectToPackage)'
      nobuild: true
      packDirectory: $(Build.ArtifactStagingDirectory)
      verbosityPack: 'Minimal'

  - task: PublishBuildArtifacts@1
    inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'NuGetPackage'
        publishLocation: 'Container'