# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
    - '*' 

pool:
  vmImage: 'ubuntu-latest'

variables:
  command: build
  projects: '$(solution)'
  configuration: '$(buildConfiguration)'
  versioningScheme: byEnvVar
  versionEnvVar: 'GitVersion.SemVer'
  buildConfiguration: 'Release'

# this pipeline has one implicit stage
jobs:
- job: Build
  steps:
    - task: UseGitVersion@5
      displayName: semverion
      inputs:
        versionSpec: '5.x'
        updateAssemblyInfo: false
    - script: dotnet build --configuration $(buildConfiguration)
      displayName: 'dotnet build $(buildConfiguration) -p:Version=$(versionEnvVar)'

- job: Tests
  steps:
  - task: DotNetCoreCLI@2
    displayName: Unit tests
    inputs:
      command: test
      projects: '*Test.csproj'
      arguments: '--configuration $(buildConfiguration)'